#pragma once

enum class DIRECTION
{
	LEFT = 0, TOP, RIGHT, BOTTOM,
	LEFT_TOP, LEFT_BOTTOM, RIGHT_TOP, RIGHT_BOTTOM,
	DIRECTION_NUM
};

std::wstring DirectionToWString(DIRECTION _dir);

enum class IMAGE_LOAD_KIND
{
	LOAD_RESOURCE = 0,
	LOAD_FILE,
	LOAD_EMPTY,
	LOAD_END,
	IMAGE_LOAD_KIND_NUM
};

enum class CHARACTER_ID
{
	AL = 0,
	KARIN,
	CHARACTER_ID_NUM
};

enum class ENEMY_TYPE
{
	SLIME,
	ENEMY_TYPE_NUM
};

enum class CHARACTER_STATE
{
	IDLE_LEFT_BOTTOM = 0,
	IDLE_LEFT_TOP,
	IDLE_RIGHT_BOTTOM,
	IDLE_RIGHT_TOP,
	MOVE_LEFT_BOTTOM,
	MOVE_LEFT_TOP,
	MOVE_RIGHT_BOTTOM,
	MOVE_RIGHT_TOP,
	ATTACK_LEFT_BOTTOM,
	ATTACK_LEFT_TOP,
	ATTACK_RIGHT_BOTTOM,
	ATTACK_RIGHT_TOP,
	ATTACKED_LEFT_BOTTOM,
	ATTACKED_LEFT_TOP,
	ATTACKED_RIGHT_BOTTOM,
	ATTACKED_RIGHT_TOP,
	CHARACTER_STATE_NUM
};

std::wstring CharacterStateToWString(CHARACTER_STATE _state);

enum class TAG
{
	UNTAGGED = 0,
	PLAYER,
	ENEMY,
	EFFECT,
	MAIN_CAMERA,
	SHOP_PANEL,
	TAG_NUM
};

std::wstring TagToWString(TAG _tag);

#pragma region FactoryType
enum class BUTTON_FACTORY_TYPE
{
	DEFAULT = 0,
	MOUSE_ON,
	BUTTON_FACTORY_TYPE_NUM
};

enum class BAR_FACTORY_TYPE
{
	DEFAULT = 0,
	BAR_FACTORY_TYPE_NUM
};

//enum class PLAYER_FACTORY_TYPE
//{
//	DEFAULT = 0,
//	PLAYER_FACTORY_TYPE_NUM
//};

enum class PLATFORM_FACTORY_TYPE
{
	DEFAULT = 0,
	PLATFORM_FACTORY_TYPE_NUM
};

enum class EFFECT_FACTORY_TYPE
{
	FLAME_BURST,
	EFFECT_FACTORY_TYPE_NUM
};
#pragma endregion FactoryType

enum class RENDERED_IMAGE_RENDERING_TYPE
{
	DEFAULT = 0,
	LOOP,
	RENDERED_IMAGE_RENDERING_TYPE
};

enum class SORTING_LAYER
{
	BACKGROUND = 0,
	BACKGROUND_EFFECT,
	PLATFORM,
	TILE,
	TILE_PANEL,
	TILE_FOCUS,
	OBJECT,
	CHARACTER,
	EFFECT,
	UI_BACKGROUND,
	UI_IMAGE,
	UI_TEXT,
	UI_EFFECT,
	DIALOG_BACKGROUND,
	DIALOG_PORTRAIT,
	DIALOG_TEXT,
	SORTING_LAYER_NUM
};

enum class EQUIP_ID
{
	NONE = 0,
	LONGSWORD,
	BROADSWORD,
	MAGICIANWAND,
	WIZARDWAND,
	CROSSARMOR,
	LEZAARMOR,
	MAGICIANROBE,
	WIZARDROBE,
	EQUIP_ID_NUM
};

enum class EQUIP_TYPE
{
	NONE = 0,
	WEAPON,
	ARMOR,
	EQUIP_TYPE_NUM
};

enum class PHASE
{
	PHASE_DIALOG,
	PHASE_SHOPPING,
	PHASE_BATTLE,
	PHASE_NUM
};

enum class PHASE_DETAIL
{
	DEFAULT,
	BATTLE_PLAYER_DEFAULT,
	BATTLE_PLAYER_CHARACTER_SELECTED,
	BATTLE_PLAYER_MOVING,
	BATTLE_PLAYER_SELECTING_DIRECTION,
	BATTLE_PLAYER_SELECTING_ACTION,
	BATTLE_PLAYER_ACTION,
	BATTLE_ENEMY_DEFAULT,
	BATTLE_ENEMY_MOVING,
	BATTLE_ENEMY_SELECTING_DIRECTION,
	BATTLE_ENEMY_SELECTING_ACTION,
	BATTLE_ENEMY_ACTION,
	PHASE_DETAIL_NUM
};

enum class EVENT
{
	DIALOG_CLICK,
	SHOP_LIST_PANEL_CLICK,
	SHOP_LIST_TO_EQUIP_CHANGE_BUTTON_CLICK,
	BUY_BUTTON_CLICK,
	EXIT_BUTTON_CLICK,
	EQUIP_CHANGE_CHARACTER_PANEL_CLICK,
	EQUIP_CHANGE_ABILITY_TAB_PANEL_CLICK,
	EQUIP_CHANGE_EQUIP_TAB_PANEL_CLICK,
	EQUIP_CHANGE_EQUIP_WEAPON_TEXT_CLICK,
	EQUIP_CHANGE_EQUIP_ARMOR_TEXT_CLICK,
	EQUIP_CHANGE_EQUIP_IN_INVEN_PANEL_CLICK,
	EQUIP_CHANGE_TO_SHOP_LIST_BUTTON_CLICK,
	EQUIP_CHANGE_EQUIP_CHANGE_BUTTON_CLICK,
	TILE_CLICK,
	TILE_CLICK_RIGHT,
	MOVE_END,
	SELECT_DIRECTION_END,
	ACTION_END,
	DIE,
	EVENT_NUM
};

enum class TILE_TYPE
{
	DIRT_Z0,
	DIRT_Z1,
	GRASS_Z0,
	GRASS_Z1,
	TILE_TYPE_NUM
};
